[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py | python3 - --break-system-packages",
  "python3 -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "python3 -m gunicorn server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
